main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,9 +22,8 @@ jobs:
         with:
           python-version: '3.10'
 
-      
       - name: Install Linting Tools
-        run: pip install --only-binary :all: flake8 black
+        run: pip install flake8 black
 
       - name: Run Flake8 (Linter)
         run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
@@ -37,10 +36,8 @@ jobs:
         with:
           dockerfile: itu-minitwit_20260128/Dockerfile
 
-
       - name: Install dependencies
-        run: |
-          pip install --only-binary :all: pytest selenium pymongo flask flask-pymongo prometheus-flask-exporter
+        run: pip install pytest selenium pymongo flask flask-pymongo prometheus-flask-exporter
 
       - name: Run Pytest
-        run: pytest test_itu_minitwit_ui.py || echo "Tests failed but continuing for now"
+        run: pytest test_itu_minitwit_ui.py || echo "Tests failed"
